version: '3'

services:

  postgres:
    image: "postgres:12"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: alura123
      POSTGRES_DB: alura-food-pagamento

volumes:
  db_data: